DELETE http://localhost:3000/order/551cc0da-dfd7-4c39-a5b9-296573d45fc3

###

POST http://localhost:3000/order
Content-Type: application/json

{
  "items": [
    {
      "productId": "3278373d-174f-467a-aaa5-82fc9957a6bf",
      "quantity": 2,
      "unitPrice": 1500
    }
  ]
}

###

GET http://localhost:3000/order

