GET http://localhost:3000/order/333bd18d-b8e9-43be-95d9-92bc06cc2089

###

POST http://localhost:3000/order
Content-Type: application/json

{
  "items": [
    {
      "productId": "fa0748cf-42b5-4ef9-865b-56340cccbfcc",
      "quantity": 4,
      "unitPrice": 10000
    }
  ]
}

###

GET http://localhost:3000/order

