syntax = "proto3";

package order;

import "google/protobuf/empty.proto";

service OrderService {
  rpc GetOrderById (OrderId) returns (Order);
  rpc GetAllOrders (google.protobuf.Empty) returns (ManyOrders);
  rpc CreateOrder (ManyItems) returns (Order);
}

message OrderId {
  string orderId = 1;
}

message OrderItems {
  string productId = 1;
  int32 quantity = 2;
  int32 unitPrice = 3;
}

message Order {
  string orderId = 1;
  int32 totalAmount = 2;
  repeated OrderItems items = 3;
}

message ManyItems {
  repeated OrderItems items = 1;
}

message ManyOrders {
  repeated Order orders = 1;
}

